services:
  web:
    build:
      context: .
    container_name: "web-task"
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    restart: always
    networks:
      - my_network

  db:
    image: postgres
    container_name: "postgres-db"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5433"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my_network

volumes:
  db_data:
  static:
  media:

networks:
  my_network:
    driver: bridge
