# Generated by Django 5.1.4 on 2025-01-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_productset_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='profession',
            field=models.CharField(max_length=100),
        ),
    ]
