# Generated by Django 5.1.4 on 2025-01-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_category_name_alter_repairservice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicerepair',
            name='product',
        ),
    ]
