# Generated by Django 5.1.4 on 2025-01-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_devicerepair_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
    ]
