# Generated by Django 5.1.4 on 2025-01-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_orderproduct_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='price',
        ),
    ]
